// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rqe_pb.proto

package rqe_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeStatus int32

const (
	NodeStatus_ONLINE       NodeStatus = 0
	NodeStatus_OFFLINE      NodeStatus = 1
	NodeStatus_TEMP_OFFLINE NodeStatus = 2
	NodeStatus_UNKNOWN      NodeStatus = 3
)

var NodeStatus_name = map[int32]string{
	0: "ONLINE",
	1: "OFFLINE",
	2: "TEMP_OFFLINE",
	3: "UNKNOWN",
}

var NodeStatus_value = map[string]int32{
	"ONLINE":       0,
	"OFFLINE":      1,
	"TEMP_OFFLINE": 2,
	"UNKNOWN":      3,
}

func (x NodeStatus) String() string {
	return proto.EnumName(NodeStatus_name, int32(x))
}

func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{0}
}

type RQItemTypeOptions_Operator int32

const (
	RQItemTypeOptions_NULL  RQItemTypeOptions_Operator = 0
	RQItemTypeOptions_GT    RQItemTypeOptions_Operator = 1
	RQItemTypeOptions_LT    RQItemTypeOptions_Operator = 2
	RQItemTypeOptions_GTE   RQItemTypeOptions_Operator = 3
	RQItemTypeOptions_LTE   RQItemTypeOptions_Operator = 4
	RQItemTypeOptions_AND   RQItemTypeOptions_Operator = 5
	RQItemTypeOptions_NOT   RQItemTypeOptions_Operator = 6
	RQItemTypeOptions_COUNT RQItemTypeOptions_Operator = 7
)

var RQItemTypeOptions_Operator_name = map[int32]string{
	0: "NULL",
	1: "GT",
	2: "LT",
	3: "GTE",
	4: "LTE",
	5: "AND",
	6: "NOT",
	7: "COUNT",
}

var RQItemTypeOptions_Operator_value = map[string]int32{
	"NULL":  0,
	"GT":    1,
	"LT":    2,
	"GTE":   3,
	"LTE":   4,
	"AND":   5,
	"NOT":   6,
	"COUNT": 7,
}

func (x RQItemTypeOptions_Operator) String() string {
	return proto.EnumName(RQItemTypeOptions_Operator_name, int32(x))
}

func (RQItemTypeOptions_Operator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{3, 0}
}

type NodeInfo struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NodeStatus           NodeStatus `protobuf:"varint,2,opt,name=node_status,json=nodeStatus,proto3,enum=NodeStatus" json:"node_status,omitempty"`
	RqCount              int32      `protobuf:"zigzag32,3,opt,name=rq_count,json=rqCount,proto3" json:"rq_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{0}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeInfo) GetNodeStatus() NodeStatus {
	if m != nil {
		return m.NodeStatus
	}
	return NodeStatus_ONLINE
}

func (m *NodeInfo) GetRqCount() int32 {
	if m != nil {
		return m.RqCount
	}
	return 0
}

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{1}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	NodeInfo             []*NodeInfo `protobuf:"bytes,1,rep,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{2}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetNodeInfo() []*NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

type RQItemTypeOptions struct {
	Operator             RQItemTypeOptions_Operator `protobuf:"varint,1,opt,name=operator,proto3,enum=RQItemTypeOptions_Operator" json:"operator,omitempty"`
	Count                int32                      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RQItemTypeOptions) Reset()         { *m = RQItemTypeOptions{} }
func (m *RQItemTypeOptions) String() string { return proto.CompactTextString(m) }
func (*RQItemTypeOptions) ProtoMessage()    {}
func (*RQItemTypeOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{3}
}

func (m *RQItemTypeOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RQItemTypeOptions.Unmarshal(m, b)
}
func (m *RQItemTypeOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RQItemTypeOptions.Marshal(b, m, deterministic)
}
func (m *RQItemTypeOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RQItemTypeOptions.Merge(m, src)
}
func (m *RQItemTypeOptions) XXX_Size() int {
	return xxx_messageInfo_RQItemTypeOptions.Size(m)
}
func (m *RQItemTypeOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_RQItemTypeOptions.DiscardUnknown(m)
}

var xxx_messageInfo_RQItemTypeOptions proto.InternalMessageInfo

func (m *RQItemTypeOptions) GetOperator() RQItemTypeOptions_Operator {
	if m != nil {
		return m.Operator
	}
	return RQItemTypeOptions_NULL
}

func (m *RQItemTypeOptions) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RQItem struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*RQItem_Integer
	//	*RQItem_String_
	//	*RQItem_Rq
	//	*RQItem_Boolean
	Value                isRQItem_Value     `protobuf_oneof:"value"`
	TypeOptions          *RQItemTypeOptions `protobuf:"bytes,6,opt,name=type_options,json=typeOptions,proto3" json:"type_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RQItem) Reset()         { *m = RQItem{} }
func (m *RQItem) String() string { return proto.CompactTextString(m) }
func (*RQItem) ProtoMessage()    {}
func (*RQItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{4}
}

func (m *RQItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RQItem.Unmarshal(m, b)
}
func (m *RQItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RQItem.Marshal(b, m, deterministic)
}
func (m *RQItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RQItem.Merge(m, src)
}
func (m *RQItem) XXX_Size() int {
	return xxx_messageInfo_RQItem.Size(m)
}
func (m *RQItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RQItem.DiscardUnknown(m)
}

var xxx_messageInfo_RQItem proto.InternalMessageInfo

func (m *RQItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type isRQItem_Value interface {
	isRQItem_Value()
}

type RQItem_Integer struct {
	Integer int32 `protobuf:"zigzag32,2,opt,name=integer,proto3,oneof"`
}

type RQItem_String_ struct {
	String_ string `protobuf:"bytes,3,opt,name=string,proto3,oneof"`
}

type RQItem_Rq struct {
	Rq *RQ `protobuf:"bytes,4,opt,name=rq,proto3,oneof"`
}

type RQItem_Boolean struct {
	Boolean bool `protobuf:"varint,5,opt,name=boolean,proto3,oneof"`
}

func (*RQItem_Integer) isRQItem_Value() {}

func (*RQItem_String_) isRQItem_Value() {}

func (*RQItem_Rq) isRQItem_Value() {}

func (*RQItem_Boolean) isRQItem_Value() {}

func (m *RQItem) GetValue() isRQItem_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RQItem) GetInteger() int32 {
	if x, ok := m.GetValue().(*RQItem_Integer); ok {
		return x.Integer
	}
	return 0
}

func (m *RQItem) GetString_() string {
	if x, ok := m.GetValue().(*RQItem_String_); ok {
		return x.String_
	}
	return ""
}

func (m *RQItem) GetRq() *RQ {
	if x, ok := m.GetValue().(*RQItem_Rq); ok {
		return x.Rq
	}
	return nil
}

func (m *RQItem) GetBoolean() bool {
	if x, ok := m.GetValue().(*RQItem_Boolean); ok {
		return x.Boolean
	}
	return false
}

func (m *RQItem) GetTypeOptions() *RQItemTypeOptions {
	if m != nil {
		return m.TypeOptions
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RQItem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RQItem_Integer)(nil),
		(*RQItem_String_)(nil),
		(*RQItem_Rq)(nil),
		(*RQItem_Boolean)(nil),
	}
}

type RQLabel struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RQLabel) Reset()         { *m = RQLabel{} }
func (m *RQLabel) String() string { return proto.CompactTextString(m) }
func (*RQLabel) ProtoMessage()    {}
func (*RQLabel) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{5}
}

func (m *RQLabel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RQLabel.Unmarshal(m, b)
}
func (m *RQLabel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RQLabel.Marshal(b, m, deterministic)
}
func (m *RQLabel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RQLabel.Merge(m, src)
}
func (m *RQLabel) XXX_Size() int {
	return xxx_messageInfo_RQLabel.Size(m)
}
func (m *RQLabel) XXX_DiscardUnknown() {
	xxx_messageInfo_RQLabel.DiscardUnknown(m)
}

var xxx_messageInfo_RQLabel proto.InternalMessageInfo

func (m *RQLabel) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RQLabel) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RQ struct {
	RqItems              []*RQItem `protobuf:"bytes,1,rep,name=rq_items,json=rqItems,proto3" json:"rq_items,omitempty"`
	Uuid                 string    `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RQ) Reset()         { *m = RQ{} }
func (m *RQ) String() string { return proto.CompactTextString(m) }
func (*RQ) ProtoMessage()    {}
func (*RQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{6}
}

func (m *RQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RQ.Unmarshal(m, b)
}
func (m *RQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RQ.Marshal(b, m, deterministic)
}
func (m *RQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RQ.Merge(m, src)
}
func (m *RQ) XXX_Size() int {
	return xxx_messageInfo_RQ.Size(m)
}
func (m *RQ) XXX_DiscardUnknown() {
	xxx_messageInfo_RQ.DiscardUnknown(m)
}

var xxx_messageInfo_RQ proto.InternalMessageInfo

func (m *RQ) GetRqItems() []*RQItem {
	if m != nil {
		return m.RqItems
	}
	return nil
}

func (m *RQ) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type AddRQRequest struct {
	Rq                   *RQ       `protobuf:"bytes,1,opt,name=rq,proto3" json:"rq,omitempty"`
	Labels               *RQLabels `protobuf:"bytes,2,opt,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddRQRequest) Reset()         { *m = AddRQRequest{} }
func (m *AddRQRequest) String() string { return proto.CompactTextString(m) }
func (*AddRQRequest) ProtoMessage()    {}
func (*AddRQRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{7}
}

func (m *AddRQRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRQRequest.Unmarshal(m, b)
}
func (m *AddRQRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRQRequest.Marshal(b, m, deterministic)
}
func (m *AddRQRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRQRequest.Merge(m, src)
}
func (m *AddRQRequest) XXX_Size() int {
	return xxx_messageInfo_AddRQRequest.Size(m)
}
func (m *AddRQRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRQRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRQRequest proto.InternalMessageInfo

func (m *AddRQRequest) GetRq() *RQ {
	if m != nil {
		return m.Rq
	}
	return nil
}

func (m *AddRQRequest) GetLabels() *RQLabels {
	if m != nil {
		return m.Labels
	}
	return nil
}

type RQLabels struct {
	Labels               []*RQLabel `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RQLabels) Reset()         { *m = RQLabels{} }
func (m *RQLabels) String() string { return proto.CompactTextString(m) }
func (*RQLabels) ProtoMessage()    {}
func (*RQLabels) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{8}
}

func (m *RQLabels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RQLabels.Unmarshal(m, b)
}
func (m *RQLabels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RQLabels.Marshal(b, m, deterministic)
}
func (m *RQLabels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RQLabels.Merge(m, src)
}
func (m *RQLabels) XXX_Size() int {
	return xxx_messageInfo_RQLabels.Size(m)
}
func (m *RQLabels) XXX_DiscardUnknown() {
	xxx_messageInfo_RQLabels.DiscardUnknown(m)
}

var xxx_messageInfo_RQLabels proto.InternalMessageInfo

func (m *RQLabels) GetLabels() []*RQLabel {
	if m != nil {
		return m.Labels
	}
	return nil
}

type AddRQResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRQResponse) Reset()         { *m = AddRQResponse{} }
func (m *AddRQResponse) String() string { return proto.CompactTextString(m) }
func (*AddRQResponse) ProtoMessage()    {}
func (*AddRQResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{9}
}

func (m *AddRQResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRQResponse.Unmarshal(m, b)
}
func (m *AddRQResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRQResponse.Marshal(b, m, deterministic)
}
func (m *AddRQResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRQResponse.Merge(m, src)
}
func (m *AddRQResponse) XXX_Size() int {
	return xxx_messageInfo_AddRQResponse.Size(m)
}
func (m *AddRQResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRQResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRQResponse proto.InternalMessageInfo

func (m *AddRQResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type DeleteRQRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRQRequest) Reset()         { *m = DeleteRQRequest{} }
func (m *DeleteRQRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRQRequest) ProtoMessage()    {}
func (*DeleteRQRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{10}
}

func (m *DeleteRQRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRQRequest.Unmarshal(m, b)
}
func (m *DeleteRQRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRQRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRQRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRQRequest.Merge(m, src)
}
func (m *DeleteRQRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRQRequest.Size(m)
}
func (m *DeleteRQRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRQRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRQRequest proto.InternalMessageInfo

func (m *DeleteRQRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type DeleteRQResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRQResponse) Reset()         { *m = DeleteRQResponse{} }
func (m *DeleteRQResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRQResponse) ProtoMessage()    {}
func (*DeleteRQResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{11}
}

func (m *DeleteRQResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRQResponse.Unmarshal(m, b)
}
func (m *DeleteRQResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRQResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRQResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRQResponse.Merge(m, src)
}
func (m *DeleteRQResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRQResponse.Size(m)
}
func (m *DeleteRQResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRQResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRQResponse proto.InternalMessageInfo

type GetRQRequest struct {
	// Types that are valid to be assigned to Field:
	//	*GetRQRequest_Uuid
	//	*GetRQRequest_Labels
	Field                isGetRQRequest_Field `protobuf_oneof:"field"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetRQRequest) Reset()         { *m = GetRQRequest{} }
func (m *GetRQRequest) String() string { return proto.CompactTextString(m) }
func (*GetRQRequest) ProtoMessage()    {}
func (*GetRQRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{12}
}

func (m *GetRQRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRQRequest.Unmarshal(m, b)
}
func (m *GetRQRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRQRequest.Marshal(b, m, deterministic)
}
func (m *GetRQRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRQRequest.Merge(m, src)
}
func (m *GetRQRequest) XXX_Size() int {
	return xxx_messageInfo_GetRQRequest.Size(m)
}
func (m *GetRQRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRQRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRQRequest proto.InternalMessageInfo

type isGetRQRequest_Field interface {
	isGetRQRequest_Field()
}

type GetRQRequest_Uuid struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3,oneof"`
}

type GetRQRequest_Labels struct {
	Labels *RQLabels `protobuf:"bytes,2,opt,name=labels,proto3,oneof"`
}

func (*GetRQRequest_Uuid) isGetRQRequest_Field() {}

func (*GetRQRequest_Labels) isGetRQRequest_Field() {}

func (m *GetRQRequest) GetField() isGetRQRequest_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *GetRQRequest) GetUuid() string {
	if x, ok := m.GetField().(*GetRQRequest_Uuid); ok {
		return x.Uuid
	}
	return ""
}

func (m *GetRQRequest) GetLabels() *RQLabels {
	if x, ok := m.GetField().(*GetRQRequest_Labels); ok {
		return x.Labels
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetRQRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetRQRequest_Uuid)(nil),
		(*GetRQRequest_Labels)(nil),
	}
}

type GetRQResponse struct {
	Rq                   *RQ       `protobuf:"bytes,1,opt,name=rq,proto3" json:"rq,omitempty"`
	Labels               *RQLabels `protobuf:"bytes,2,opt,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetRQResponse) Reset()         { *m = GetRQResponse{} }
func (m *GetRQResponse) String() string { return proto.CompactTextString(m) }
func (*GetRQResponse) ProtoMessage()    {}
func (*GetRQResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{13}
}

func (m *GetRQResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRQResponse.Unmarshal(m, b)
}
func (m *GetRQResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRQResponse.Marshal(b, m, deterministic)
}
func (m *GetRQResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRQResponse.Merge(m, src)
}
func (m *GetRQResponse) XXX_Size() int {
	return xxx_messageInfo_GetRQResponse.Size(m)
}
func (m *GetRQResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRQResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRQResponse proto.InternalMessageInfo

func (m *GetRQResponse) GetRq() *RQ {
	if m != nil {
		return m.Rq
	}
	return nil
}

func (m *GetRQResponse) GetLabels() *RQLabels {
	if m != nil {
		return m.Labels
	}
	return nil
}

type MatchEntryRequest struct {
	Entry                map[string]*MatchEntryRequest_EntryValue `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timeout              int32                                    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *MatchEntryRequest) Reset()         { *m = MatchEntryRequest{} }
func (m *MatchEntryRequest) String() string { return proto.CompactTextString(m) }
func (*MatchEntryRequest) ProtoMessage()    {}
func (*MatchEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{14}
}

func (m *MatchEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchEntryRequest.Unmarshal(m, b)
}
func (m *MatchEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchEntryRequest.Marshal(b, m, deterministic)
}
func (m *MatchEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchEntryRequest.Merge(m, src)
}
func (m *MatchEntryRequest) XXX_Size() int {
	return xxx_messageInfo_MatchEntryRequest.Size(m)
}
func (m *MatchEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MatchEntryRequest proto.InternalMessageInfo

func (m *MatchEntryRequest) GetEntry() map[string]*MatchEntryRequest_EntryValue {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *MatchEntryRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type MatchEntryRequest_EntryValue struct {
	// Types that are valid to be assigned to Value:
	//	*MatchEntryRequest_EntryValue_String_
	//	*MatchEntryRequest_EntryValue_Integer
	//	*MatchEntryRequest_EntryValue_Boolean
	Value                isMatchEntryRequest_EntryValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *MatchEntryRequest_EntryValue) Reset()         { *m = MatchEntryRequest_EntryValue{} }
func (m *MatchEntryRequest_EntryValue) String() string { return proto.CompactTextString(m) }
func (*MatchEntryRequest_EntryValue) ProtoMessage()    {}
func (*MatchEntryRequest_EntryValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{14, 0}
}

func (m *MatchEntryRequest_EntryValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchEntryRequest_EntryValue.Unmarshal(m, b)
}
func (m *MatchEntryRequest_EntryValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchEntryRequest_EntryValue.Marshal(b, m, deterministic)
}
func (m *MatchEntryRequest_EntryValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchEntryRequest_EntryValue.Merge(m, src)
}
func (m *MatchEntryRequest_EntryValue) XXX_Size() int {
	return xxx_messageInfo_MatchEntryRequest_EntryValue.Size(m)
}
func (m *MatchEntryRequest_EntryValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchEntryRequest_EntryValue.DiscardUnknown(m)
}

var xxx_messageInfo_MatchEntryRequest_EntryValue proto.InternalMessageInfo

type isMatchEntryRequest_EntryValue_Value interface {
	isMatchEntryRequest_EntryValue_Value()
}

type MatchEntryRequest_EntryValue_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type MatchEntryRequest_EntryValue_Integer struct {
	Integer int32 `protobuf:"zigzag32,2,opt,name=integer,proto3,oneof"`
}

type MatchEntryRequest_EntryValue_Boolean struct {
	Boolean bool `protobuf:"varint,3,opt,name=boolean,proto3,oneof"`
}

func (*MatchEntryRequest_EntryValue_String_) isMatchEntryRequest_EntryValue_Value() {}

func (*MatchEntryRequest_EntryValue_Integer) isMatchEntryRequest_EntryValue_Value() {}

func (*MatchEntryRequest_EntryValue_Boolean) isMatchEntryRequest_EntryValue_Value() {}

func (m *MatchEntryRequest_EntryValue) GetValue() isMatchEntryRequest_EntryValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MatchEntryRequest_EntryValue) GetString_() string {
	if x, ok := m.GetValue().(*MatchEntryRequest_EntryValue_String_); ok {
		return x.String_
	}
	return ""
}

func (m *MatchEntryRequest_EntryValue) GetInteger() int32 {
	if x, ok := m.GetValue().(*MatchEntryRequest_EntryValue_Integer); ok {
		return x.Integer
	}
	return 0
}

func (m *MatchEntryRequest_EntryValue) GetBoolean() bool {
	if x, ok := m.GetValue().(*MatchEntryRequest_EntryValue_Boolean); ok {
		return x.Boolean
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MatchEntryRequest_EntryValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MatchEntryRequest_EntryValue_String_)(nil),
		(*MatchEntryRequest_EntryValue_Integer)(nil),
		(*MatchEntryRequest_EntryValue_Boolean)(nil),
	}
}

type MatchEntryResponse struct {
	Rqs                  []*RQ    `protobuf:"bytes,1,rep,name=rqs,proto3" json:"rqs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchEntryResponse) Reset()         { *m = MatchEntryResponse{} }
func (m *MatchEntryResponse) String() string { return proto.CompactTextString(m) }
func (*MatchEntryResponse) ProtoMessage()    {}
func (*MatchEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{15}
}

func (m *MatchEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchEntryResponse.Unmarshal(m, b)
}
func (m *MatchEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchEntryResponse.Marshal(b, m, deterministic)
}
func (m *MatchEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchEntryResponse.Merge(m, src)
}
func (m *MatchEntryResponse) XXX_Size() int {
	return xxx_messageInfo_MatchEntryResponse.Size(m)
}
func (m *MatchEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MatchEntryResponse proto.InternalMessageInfo

func (m *MatchEntryResponse) GetRqs() []*RQ {
	if m != nil {
		return m.Rqs
	}
	return nil
}

type AddNodeRequest struct {
	Node                 string   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Module               string   `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeRequest) Reset()         { *m = AddNodeRequest{} }
func (m *AddNodeRequest) String() string { return proto.CompactTextString(m) }
func (*AddNodeRequest) ProtoMessage()    {}
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{16}
}

func (m *AddNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeRequest.Unmarshal(m, b)
}
func (m *AddNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeRequest.Marshal(b, m, deterministic)
}
func (m *AddNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeRequest.Merge(m, src)
}
func (m *AddNodeRequest) XXX_Size() int {
	return xxx_messageInfo_AddNodeRequest.Size(m)
}
func (m *AddNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeRequest proto.InternalMessageInfo

func (m *AddNodeRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *AddNodeRequest) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

type AddNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeResponse) Reset()         { *m = AddNodeResponse{} }
func (m *AddNodeResponse) String() string { return proto.CompactTextString(m) }
func (*AddNodeResponse) ProtoMessage()    {}
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{17}
}

func (m *AddNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeResponse.Unmarshal(m, b)
}
func (m *AddNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeResponse.Marshal(b, m, deterministic)
}
func (m *AddNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeResponse.Merge(m, src)
}
func (m *AddNodeResponse) XXX_Size() int {
	return xxx_messageInfo_AddNodeResponse.Size(m)
}
func (m *AddNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeResponse proto.InternalMessageInfo

type Request struct {
	// Types that are valid to be assigned to Msg:
	//	*Request_StatusRequest
	//	*Request_AddRqRequest
	//	*Request_DeleteRqRequest
	//	*Request_GetRqRequest
	//	*Request_MatchEntryRequest
	//	*Request_AddNodeRequest
	Msg                  isRequest_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{18}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type isRequest_Msg interface {
	isRequest_Msg()
}

type Request_StatusRequest struct {
	StatusRequest *StatusRequest `protobuf:"bytes,1,opt,name=status_request,json=statusRequest,proto3,oneof"`
}

type Request_AddRqRequest struct {
	AddRqRequest *AddRQRequest `protobuf:"bytes,2,opt,name=add_rq_request,json=addRqRequest,proto3,oneof"`
}

type Request_DeleteRqRequest struct {
	DeleteRqRequest *DeleteRQRequest `protobuf:"bytes,3,opt,name=delete_rq_request,json=deleteRqRequest,proto3,oneof"`
}

type Request_GetRqRequest struct {
	GetRqRequest *GetRQRequest `protobuf:"bytes,4,opt,name=get_rq_request,json=getRqRequest,proto3,oneof"`
}

type Request_MatchEntryRequest struct {
	MatchEntryRequest *MatchEntryRequest `protobuf:"bytes,5,opt,name=match_entry_request,json=matchEntryRequest,proto3,oneof"`
}

type Request_AddNodeRequest struct {
	AddNodeRequest *AddNodeRequest `protobuf:"bytes,6,opt,name=add_node_request,json=addNodeRequest,proto3,oneof"`
}

func (*Request_StatusRequest) isRequest_Msg() {}

func (*Request_AddRqRequest) isRequest_Msg() {}

func (*Request_DeleteRqRequest) isRequest_Msg() {}

func (*Request_GetRqRequest) isRequest_Msg() {}

func (*Request_MatchEntryRequest) isRequest_Msg() {}

func (*Request_AddNodeRequest) isRequest_Msg() {}

func (m *Request) GetMsg() isRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Request) GetStatusRequest() *StatusRequest {
	if x, ok := m.GetMsg().(*Request_StatusRequest); ok {
		return x.StatusRequest
	}
	return nil
}

func (m *Request) GetAddRqRequest() *AddRQRequest {
	if x, ok := m.GetMsg().(*Request_AddRqRequest); ok {
		return x.AddRqRequest
	}
	return nil
}

func (m *Request) GetDeleteRqRequest() *DeleteRQRequest {
	if x, ok := m.GetMsg().(*Request_DeleteRqRequest); ok {
		return x.DeleteRqRequest
	}
	return nil
}

func (m *Request) GetGetRqRequest() *GetRQRequest {
	if x, ok := m.GetMsg().(*Request_GetRqRequest); ok {
		return x.GetRqRequest
	}
	return nil
}

func (m *Request) GetMatchEntryRequest() *MatchEntryRequest {
	if x, ok := m.GetMsg().(*Request_MatchEntryRequest); ok {
		return x.MatchEntryRequest
	}
	return nil
}

func (m *Request) GetAddNodeRequest() *AddNodeRequest {
	if x, ok := m.GetMsg().(*Request_AddNodeRequest); ok {
		return x.AddNodeRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_StatusRequest)(nil),
		(*Request_AddRqRequest)(nil),
		(*Request_DeleteRqRequest)(nil),
		(*Request_GetRqRequest)(nil),
		(*Request_MatchEntryRequest)(nil),
		(*Request_AddNodeRequest)(nil),
	}
}

type Response struct {
	// Types that are valid to be assigned to Msg:
	//	*Response_StatusResponse
	//	*Response_AddRqResponse
	//	*Response_DeleteRqResponse
	//	*Response_GetRqResponse
	//	*Response_MatchEntryResponse
	//	*Response_AddNodeResponse
	Msg                  isResponse_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_de38afa53ccb7219, []int{19}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type isResponse_Msg interface {
	isResponse_Msg()
}

type Response_StatusResponse struct {
	StatusResponse *StatusResponse `protobuf:"bytes,1,opt,name=status_response,json=statusResponse,proto3,oneof"`
}

type Response_AddRqResponse struct {
	AddRqResponse *AddRQResponse `protobuf:"bytes,2,opt,name=add_rq_response,json=addRqResponse,proto3,oneof"`
}

type Response_DeleteRqResponse struct {
	DeleteRqResponse *DeleteRQResponse `protobuf:"bytes,3,opt,name=delete_rq_response,json=deleteRqResponse,proto3,oneof"`
}

type Response_GetRqResponse struct {
	GetRqResponse *GetRQResponse `protobuf:"bytes,4,opt,name=get_rq_response,json=getRqResponse,proto3,oneof"`
}

type Response_MatchEntryResponse struct {
	MatchEntryResponse *MatchEntryResponse `protobuf:"bytes,5,opt,name=match_entry_response,json=matchEntryResponse,proto3,oneof"`
}

type Response_AddNodeResponse struct {
	AddNodeResponse *AddNodeResponse `protobuf:"bytes,6,opt,name=add_node_response,json=addNodeResponse,proto3,oneof"`
}

func (*Response_StatusResponse) isResponse_Msg() {}

func (*Response_AddRqResponse) isResponse_Msg() {}

func (*Response_DeleteRqResponse) isResponse_Msg() {}

func (*Response_GetRqResponse) isResponse_Msg() {}

func (*Response_MatchEntryResponse) isResponse_Msg() {}

func (*Response_AddNodeResponse) isResponse_Msg() {}

func (m *Response) GetMsg() isResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Response) GetStatusResponse() *StatusResponse {
	if x, ok := m.GetMsg().(*Response_StatusResponse); ok {
		return x.StatusResponse
	}
	return nil
}

func (m *Response) GetAddRqResponse() *AddRQResponse {
	if x, ok := m.GetMsg().(*Response_AddRqResponse); ok {
		return x.AddRqResponse
	}
	return nil
}

func (m *Response) GetDeleteRqResponse() *DeleteRQResponse {
	if x, ok := m.GetMsg().(*Response_DeleteRqResponse); ok {
		return x.DeleteRqResponse
	}
	return nil
}

func (m *Response) GetGetRqResponse() *GetRQResponse {
	if x, ok := m.GetMsg().(*Response_GetRqResponse); ok {
		return x.GetRqResponse
	}
	return nil
}

func (m *Response) GetMatchEntryResponse() *MatchEntryResponse {
	if x, ok := m.GetMsg().(*Response_MatchEntryResponse); ok {
		return x.MatchEntryResponse
	}
	return nil
}

func (m *Response) GetAddNodeResponse() *AddNodeResponse {
	if x, ok := m.GetMsg().(*Response_AddNodeResponse); ok {
		return x.AddNodeResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_StatusResponse)(nil),
		(*Response_AddRqResponse)(nil),
		(*Response_DeleteRqResponse)(nil),
		(*Response_GetRqResponse)(nil),
		(*Response_MatchEntryResponse)(nil),
		(*Response_AddNodeResponse)(nil),
	}
}

func init() {
	proto.RegisterEnum("NodeStatus", NodeStatus_name, NodeStatus_value)
	proto.RegisterEnum("RQItemTypeOptions_Operator", RQItemTypeOptions_Operator_name, RQItemTypeOptions_Operator_value)
	proto.RegisterType((*NodeInfo)(nil), "NodeInfo")
	proto.RegisterType((*StatusRequest)(nil), "StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "StatusResponse")
	proto.RegisterType((*RQItemTypeOptions)(nil), "RQItemTypeOptions")
	proto.RegisterType((*RQItem)(nil), "RQItem")
	proto.RegisterType((*RQLabel)(nil), "RQLabel")
	proto.RegisterType((*RQ)(nil), "RQ")
	proto.RegisterType((*AddRQRequest)(nil), "AddRQRequest")
	proto.RegisterType((*RQLabels)(nil), "RQLabels")
	proto.RegisterType((*AddRQResponse)(nil), "AddRQResponse")
	proto.RegisterType((*DeleteRQRequest)(nil), "DeleteRQRequest")
	proto.RegisterType((*DeleteRQResponse)(nil), "DeleteRQResponse")
	proto.RegisterType((*GetRQRequest)(nil), "GetRQRequest")
	proto.RegisterType((*GetRQResponse)(nil), "GetRQResponse")
	proto.RegisterType((*MatchEntryRequest)(nil), "MatchEntryRequest")
	proto.RegisterMapType((map[string]*MatchEntryRequest_EntryValue)(nil), "MatchEntryRequest.EntryEntry")
	proto.RegisterType((*MatchEntryRequest_EntryValue)(nil), "MatchEntryRequest.EntryValue")
	proto.RegisterType((*MatchEntryResponse)(nil), "MatchEntryResponse")
	proto.RegisterType((*AddNodeRequest)(nil), "AddNodeRequest")
	proto.RegisterType((*AddNodeResponse)(nil), "AddNodeResponse")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("rqe_pb.proto", fileDescriptor_de38afa53ccb7219) }

var fileDescriptor_de38afa53ccb7219 = []byte{
	// 1049 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xef, 0x6e, 0xe2, 0x46,
	0x10, 0xf7, 0x1f, 0xc0, 0x66, 0x20, 0x60, 0x36, 0xb9, 0x8a, 0xa6, 0xaa, 0x44, 0x1d, 0xb5, 0x42,
	0xed, 0xc9, 0xd2, 0x25, 0x8a, 0x2e, 0xba, 0x9e, 0x4e, 0xca, 0x5d, 0xfe, 0x38, 0x2a, 0x31, 0xcd,
	0x86, 0xf4, 0x3e, 0x22, 0x27, 0xde, 0x50, 0x54, 0xb0, 0xb1, 0xbd, 0x9c, 0x94, 0x87, 0xe8, 0x5b,
	0xf4, 0x1d, 0xfa, 0x00, 0x7d, 0xab, 0x7e, 0xaa, 0x76, 0x3d, 0x36, 0x06, 0xd2, 0xfb, 0x70, 0x5f,
	0x60, 0x67, 0x3c, 0xbf, 0xdd, 0x99, 0xf9, 0xfd, 0x76, 0x6c, 0x68, 0x26, 0x31, 0x1b, 0x2f, 0xee,
	0x9d, 0x45, 0x12, 0xf1, 0xc8, 0x9e, 0x80, 0xe9, 0x45, 0x01, 0xbb, 0x0a, 0x1f, 0x23, 0x42, 0xa0,
	0x12, 0xfa, 0x73, 0xd6, 0x55, 0x7b, 0x6a, 0xbf, 0x4e, 0xe5, 0x9a, 0xbc, 0x84, 0x46, 0x18, 0x05,
	0x6c, 0x9c, 0x72, 0x9f, 0x2f, 0xd3, 0xae, 0xd6, 0x53, 0xfb, 0xad, 0xc3, 0x86, 0x23, 0x30, 0xb7,
	0xd2, 0x45, 0x21, 0x2c, 0xd6, 0xe4, 0x6b, 0x30, 0x93, 0x78, 0xfc, 0x10, 0x2d, 0x43, 0xde, 0xd5,
	0x7b, 0x6a, 0xbf, 0x43, 0x8d, 0x24, 0xfe, 0x20, 0x4c, 0xbb, 0x0d, 0x3b, 0x08, 0x60, 0xf1, 0x92,
	0xa5, 0xdc, 0x3e, 0x81, 0x56, 0xee, 0x48, 0x17, 0x51, 0x98, 0x32, 0xf2, 0x03, 0xd4, 0xe5, 0x59,
	0xd3, 0xf0, 0x31, 0xea, 0xaa, 0x3d, 0xbd, 0xdf, 0x38, 0xac, 0x3b, 0x79, 0x76, 0xd4, 0x0c, 0x71,
	0x65, 0xff, 0xad, 0x42, 0x87, 0xde, 0x5c, 0x71, 0x36, 0x1f, 0x3d, 0x2d, 0xd8, 0x70, 0xc1, 0xa7,
	0x51, 0x98, 0x92, 0xd7, 0x60, 0x46, 0x0b, 0x96, 0xf8, 0x3c, 0x4a, 0x64, 0x05, 0xad, 0xc3, 0x6f,
	0x9c, 0xad, 0x28, 0x67, 0x88, 0x21, 0xb4, 0x08, 0x26, 0x7b, 0x50, 0xcd, 0x32, 0x16, 0xc5, 0x55,
	0x69, 0x66, 0xd8, 0xb7, 0x60, 0xe6, 0xb1, 0xc4, 0x84, 0x8a, 0x77, 0x37, 0x18, 0x58, 0x0a, 0xa9,
	0x81, 0x76, 0x39, 0xb2, 0x54, 0xf1, 0x3f, 0x18, 0x59, 0x1a, 0x31, 0x40, 0xbf, 0x1c, 0x9d, 0x5b,
	0xba, 0x58, 0x0c, 0x46, 0xe7, 0x56, 0x45, 0x2c, 0x4e, 0xbd, 0x33, 0xab, 0x2a, 0x16, 0xde, 0x70,
	0x64, 0xd5, 0x48, 0x1d, 0xaa, 0x1f, 0x86, 0x77, 0xde, 0xc8, 0x32, 0xec, 0x7f, 0x54, 0xa8, 0x65,
	0x39, 0x11, 0x0b, 0xf4, 0x3f, 0xd8, 0x13, 0xf6, 0x5a, 0x2c, 0xc9, 0x3e, 0x18, 0xd3, 0x90, 0xb3,
	0x09, 0x4b, 0x64, 0x26, 0x1d, 0x57, 0xa1, 0xb9, 0x83, 0x74, 0xa1, 0x96, 0xf2, 0x64, 0x1a, 0x4e,
	0x64, 0x5b, 0xeb, 0xae, 0x42, 0xd1, 0x26, 0x2f, 0x40, 0x4b, 0xe2, 0x6e, 0xa5, 0xa7, 0xf6, 0x1b,
	0x87, 0xba, 0x43, 0x6f, 0x5c, 0x85, 0x6a, 0x49, 0x2c, 0x36, 0xbb, 0x8f, 0xa2, 0x19, 0xf3, 0xc3,
	0x6e, 0xb5, 0xa7, 0xf6, 0x4d, 0xb1, 0x19, 0x3a, 0xc8, 0x31, 0x34, 0xf9, 0xd3, 0x82, 0x8d, 0xa3,
	0xac, 0x27, 0xdd, 0x9a, 0x04, 0x93, 0xed, 0x6e, 0xd1, 0x06, 0x5f, 0x19, 0xef, 0x0d, 0xa8, 0x7e,
	0xf2, 0x67, 0x4b, 0x66, 0xbf, 0x02, 0x83, 0xde, 0x0c, 0xfc, 0x7b, 0x36, 0x7b, 0xa6, 0x8a, 0x3d,
	0x8c, 0x92, 0x35, 0xd4, 0x29, 0x42, 0xde, 0x82, 0x46, 0x6f, 0x88, 0x2d, 0xe5, 0x31, 0xe5, 0x6c,
	0x9e, 0x22, 0xbf, 0x06, 0x1e, 0x2a, 0x74, 0x22, 0xfe, 0x53, 0x21, 0xc2, 0xe5, 0x72, 0x1a, 0x20,
	0x5c, 0xae, 0xed, 0x0b, 0x68, 0x9e, 0x06, 0x01, 0xbd, 0x41, 0xe9, 0x90, 0x5d, 0x59, 0xb3, 0x5a,
	0xd4, 0x2c, 0x2b, 0xfe, 0x0e, 0x6a, 0x33, 0x91, 0x53, 0x26, 0x52, 0x21, 0x1d, 0x4c, 0x32, 0xa5,
	0xf8, 0xc0, 0x7e, 0x09, 0x66, 0xee, 0x23, 0xbd, 0x22, 0x3c, 0xcb, 0xc4, 0xcc, 0xc3, 0x8b, 0xe8,
	0x03, 0xd8, 0xc1, 0x53, 0x51, 0x9f, 0x79, 0x6a, 0x6a, 0x29, 0xb5, 0xef, 0xa1, 0x7d, 0xc6, 0x66,
	0x8c, 0xb3, 0x55, 0x76, 0xcf, 0x85, 0x11, 0xb0, 0x56, 0x61, 0xd9, 0x76, 0x36, 0x85, 0xe6, 0x25,
	0xe3, 0x2b, 0xdc, 0x5e, 0x19, 0xe7, 0x2a, 0x19, 0x92, 0x1c, 0xfc, 0x6f, 0x59, 0x42, 0x04, 0xd9,
	0x23, 0x41, 0xcd, 0xe3, 0x94, 0xcd, 0x02, 0xfb, 0x12, 0x76, 0x70, 0x4f, 0xcc, 0xf9, 0x4b, 0x5b,
	0xf5, 0x97, 0x06, 0x9d, 0x6b, 0x9f, 0x3f, 0xfc, 0x7e, 0x1e, 0xf2, 0xe4, 0x29, 0x4f, 0xf1, 0x08,
	0xaa, 0x4c, 0xd8, 0xd8, 0xb3, 0x6f, 0x9d, 0xad, 0x10, 0x47, 0x1a, 0x99, 0x27, 0x8b, 0x25, 0x5d,
	0x30, 0xf8, 0x74, 0xce, 0xa2, 0x65, 0x7e, 0xc3, 0x72, 0x73, 0x7f, 0x02, 0x20, 0x23, 0x7f, 0x13,
	0x1a, 0x29, 0x69, 0x5c, 0xdd, 0xd0, 0xf8, 0xe7, 0x6e, 0x46, 0x49, 0xe8, 0xfa, 0x86, 0xd0, 0x0b,
	0xc5, 0xee, 0x7f, 0xc4, 0x83, 0xe4, 0xcf, 0x33, 0xa2, 0x3d, 0x2a, 0x8b, 0xf6, 0x33, 0x75, 0xc9,
	0x44, 0x51, 0xd3, 0x6f, 0xb4, 0x13, 0xd5, 0xfe, 0x09, 0x48, 0x39, 0x14, 0x9b, 0xfe, 0x02, 0xf4,
	0x24, 0xce, 0x85, 0x25, 0xbb, 0x2e, 0x6c, 0xfb, 0x2d, 0xb4, 0x4e, 0x83, 0x40, 0x0c, 0xb4, 0x92,
	0x54, 0xc4, 0x54, 0x2b, 0x26, 0x6e, 0x14, 0x30, 0xf2, 0x15, 0xd4, 0xe6, 0x51, 0xb0, 0x9c, 0xe5,
	0x37, 0x08, 0x2d, 0xbb, 0x03, 0xed, 0x02, 0x8d, 0x0a, 0xfa, 0x57, 0x03, 0x23, 0xdf, 0xea, 0x35,
	0xb4, 0xb2, 0x19, 0x3d, 0x4e, 0x32, 0x0f, 0x92, 0xde, 0x72, 0xd6, 0xc6, 0xae, 0xab, 0xd0, 0x9d,
	0xb4, 0xec, 0x20, 0xc7, 0xd0, 0xf2, 0x83, 0x60, 0x9c, 0xc4, 0x05, 0x30, 0x6b, 0xc2, 0x8e, 0x53,
	0xbe, 0x73, 0xae, 0x42, 0x9b, 0x7e, 0x10, 0xd0, 0x38, 0x87, 0xbd, 0x83, 0x4e, 0x20, 0x15, 0x5d,
	0x46, 0xea, 0x12, 0x69, 0x39, 0x1b, 0x57, 0xc2, 0x55, 0x68, 0x3b, 0x0b, 0x5e, 0xe1, 0x8f, 0xa1,
	0x35, 0x61, 0xbc, 0x0c, 0xae, 0xe0, 0xb1, 0xe5, 0x4b, 0x21, 0x8e, 0x9d, 0x30, 0xbe, 0x82, 0x9d,
	0xc1, 0xee, 0x5c, 0x34, 0x7c, 0x2c, 0xb5, 0x55, 0x60, 0xab, 0x38, 0xc2, 0xb6, 0x78, 0x73, 0x15,
	0xda, 0x99, 0x6f, 0xe9, 0xf8, 0x67, 0xb0, 0x44, 0xcd, 0xf2, 0x6d, 0x93, 0x6f, 0x91, 0x4d, 0xc1,
	0xb6, 0xb3, 0x4e, 0x91, 0xab, 0x50, 0xd1, 0x9e, 0x92, 0xe7, 0x7d, 0x15, 0xf4, 0x79, 0x3a, 0xb1,
	0xff, 0xd4, 0xc1, 0x2c, 0x18, 0x7f, 0x03, 0xed, 0xa2, 0xfb, 0x99, 0x0b, 0xdb, 0xdf, 0x76, 0xd6,
	0x5f, 0x72, 0x62, 0xbf, 0x74, 0xfd, 0xb5, 0x77, 0x02, 0xed, 0x82, 0x00, 0xc4, 0x6a, 0x48, 0xdd,
	0xda, 0xfc, 0x11, 0xd4, 0x21, 0x05, 0x88, 0x3c, 0x05, 0x52, 0xe6, 0x00, 0xc1, 0x19, 0x09, 0x1d,
	0x67, 0x73, 0xe0, 0xb8, 0x0a, 0xb5, 0x56, 0x2c, 0xac, 0x0e, 0x2f, 0x68, 0x40, 0x7c, 0x05, 0x0f,
	0x5f, 0x1b, 0x24, 0xe2, 0x70, 0x24, 0x02, 0x91, 0x97, 0xb0, 0xb7, 0xce, 0x04, 0xc2, 0x33, 0x2a,
	0x76, 0x9d, 0xed, 0x7b, 0xe1, 0x2a, 0x94, 0xcc, 0xb7, 0x6f, 0xcb, 0x3b, 0xe8, 0x94, 0xc8, 0xc0,
	0x5d, 0x6a, 0xa8, 0xa4, 0x0d, 0xc9, 0x0b, 0x25, 0xf9, 0xeb, 0x2e, 0xe4, 0xe3, 0xc7, 0x33, 0x80,
	0xd5, 0x57, 0x09, 0x01, 0xa8, 0x0d, 0xbd, 0xc1, 0x95, 0x77, 0x6e, 0x29, 0xa4, 0x01, 0xc6, 0xf0,
	0xe2, 0x42, 0x1a, 0x2a, 0xb1, 0xa0, 0x39, 0x3a, 0xbf, 0xfe, 0x75, 0x9c, 0x7b, 0x34, 0xf1, 0xf8,
	0xce, 0xfb, 0xc5, 0x1b, 0x7e, 0xf4, 0x2c, 0xfd, 0xf0, 0x15, 0x40, 0x12, 0xb3, 0x5b, 0x96, 0x7c,
	0x9a, 0x3e, 0x30, 0x72, 0x20, 0xad, 0x6b, 0x96, 0xa6, 0xfe, 0x84, 0x11, 0xd3, 0x41, 0x09, 0xec,
	0xd7, 0x9d, 0xe2, 0x0e, 0x2a, 0xf7, 0x35, 0xf9, 0x25, 0x75, 0xf4, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x39, 0xec, 0xa1, 0x2c, 0x59, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RqeServiceClient is the client API for RqeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RqeServiceClient interface {
	RqeMessage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type rqeServiceClient struct {
	cc *grpc.ClientConn
}

func NewRqeServiceClient(cc *grpc.ClientConn) RqeServiceClient {
	return &rqeServiceClient{cc}
}

func (c *rqeServiceClient) RqeMessage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rqeService/rqeMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RqeServiceServer is the server API for RqeService service.
type RqeServiceServer interface {
	RqeMessage(context.Context, *Request) (*Response, error)
}

// UnimplementedRqeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRqeServiceServer struct {
}

func (*UnimplementedRqeServiceServer) RqeMessage(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RqeMessage not implemented")
}

func RegisterRqeServiceServer(s *grpc.Server, srv RqeServiceServer) {
	s.RegisterService(&_RqeService_serviceDesc, srv)
}

func _RqeService_RqeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RqeServiceServer).RqeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rqeService/RqeMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RqeServiceServer).RqeMessage(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _RqeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rqeService",
	HandlerType: (*RqeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "rqeMessage",
			Handler:    _RqeService_RqeMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rqe_pb.proto",
}
